export const products = [
  {
    id: 22,
    name: "26' Foot Mid-Lite Canopy",
    animal: 'cats',
    slug: '26-foot-mid-lite-canopy',
    category: 'accessories',
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30'],
    brand: 'Tactical Kingdom',
    description:
      'A durable and weather-resistant canopy for outdoor events. Fits lions up to 500 lbs.',
    stock: 100,
    price: 1924.99,
    rating: 0,
    numReviews: 0,
    isFeatured: true,
    createdAt: new Date(),
    variants: [
      { optionA: 'Red', optionB: 'Small', stock: 10, price: 1924.99 },
      { optionA: 'Red', optionB: 'Medium', stock: 5, price: 1924.99 },
      { optionA: 'Red', optionB: 'Large', stock: 2, price: 1924.99 },
      { optionA: 'Blue', optionB: 'Small', stock: 8, price: 1924.99 },
      { optionA: 'Blue', optionB: 'Medium', stock: 4, price: 1924.99 },
      { optionA: 'Blue', optionB: 'Large', stock: 1, price: 1924.99 },
      { optionA: 'Green', optionB: 'Small', stock: 12, price: 1924.99 },
      { optionA: 'Green', optionB: 'Medium', stock: 6, price: 1924.99 },
      { optionA: 'Green', optionB: 'Large', stock: 3, price: 1924.99 },
    ],
  },
  {
    id: 22,
    name: 'Wolf 4K Night Vision Goggles– 10X Optical & 8X Digital Zoom',
    animal: 'dogs',
    slug: '4k-night-vision-goggles',
    category: 'accessories',
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30'],
    brand: 'Tactical Kingdom',
    description:
      'A durable and weather-resistant canopy for outdoor events. Fits lions up to 500 lbs.',
    stock: 100,
    price: 129.99,
    rating: 0,
    numReviews: 0,
    isFeatured: true,
    createdAt: new Date(),
    variants: [
      { optionA: 'Red', optionB: 'Small', stock: 10, price: 1924.99 },
      { optionA: 'Red', optionB: 'Medium', stock: 5, price: 1924.99 },
      { optionA: 'Red', optionB: 'Large', stock: 2, price: 1924.99 },
      { optionA: 'Blue', optionB: 'Small', stock: 8, price: 1924.99 },
      { optionA: 'Blue', optionB: 'Medium', stock: 4, price: 1924.99 },
      { optionA: 'Blue', optionB: 'Large', stock: 1, price: 1924.99 },
      { optionA: 'Green', optionB: 'Small', stock: 12, price: 1924.99 },
      { optionA: 'Green', optionB: 'Medium', stock: 6, price: 1924.99 },
      { optionA: 'Green', optionB: 'Large', stock: 3, price: 1924.99 },
    ],
  },
];
