import { Button } from '@/components/ui/button';
import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <div className="bg-white py-2">
          <div className="flex flex-row justify-between w-full max-w-5xl mx-auto">
            <Button asChild variant={'secondary'} className="font-bold mx-4">
              <Link href="/admin/orders">Orders</Link>
            </Button>
            <Button asChild variant={'secondary'} className="font-bold mx-4">
              <Link href="/admin/products">Products</Link>
            </Button>
            <Button asChild variant={'secondary'} className="font-bold mx-4">
              <Link href="/admin/users">Users</Link>
            </Button>
          </div>
        </div>
        <div>{children}</div>
      </body>
    </html>
  );
}
